#!/usr/bin/env bash
# Update package list
apt-get -y update
# Install HAProxy
apt-get -y install haproxy

# Configure HAProxy
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    maxconn 4096
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option redispatch
    retries 3
    timeout http-request 10s
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout http-keep-alive 10s
    timeout check 10s

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 1733-web-01 3.235.21.36:80 check
    server 1733-web-02 3.227.3.18:80 check
EOL

# Restart HAProxy to apply changes
service haproxy restart

# Ensure HAProxy starts on boot
update-rc.d haproxy defaults

