#!/usr/bin/env bash
# Function to handle SIGTERM and SIGQUIT signals

function cleanup() 
{
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 1
}

# Function to handle SIGINT signal
function interrupt() 
{
    echo "Y U no love me?!"
}

# Register signal handlers
trap 'cleanup' SIGTERM SIGQUIT
trap 'interrupt' SIGINT

# Create the PID file
echo $$ > /var/run/myscript.pid

# Main loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done

