#!/usr/bin/env bash
# Get the PID of the 7-highlander process

highlander_pid=$(pgrep -x 7-highlander)

# Check if the process exists and send the SIGTERM signal if it does
if [ -n "$highlander_pid" ]; then
    kill -TERM "$highlander_pid"
fi

