#!/usr/bin/env bash
#a Bash script that displays the content of the file

while IFS=':' read -r username x uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $gecos"
done < /etc/passwd

