#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, it displays "Best School" on one line and "Hi" on a new line.

count=1
while [ $count -le 10 ];
do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done

