#!/usr/bin/env bash
#displays the content of the current directory in a list format

for file in *; do
    if [ -f "$file" ] && [[ $file == *-* ]]; then
        name=${file#*-}
        echo "$name"
    fi
done

