#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

# Create a temporary file
temp_hosts=$(mktemp)

# Copy /etc/hosts to the temporary file
cp /etc/hosts "$temp_hosts"

# Replace localhost and facebook.com entries in the temporary file
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' "$temp_hosts"

# Overwrite the original /etc/hosts file with the modified temporary file
sudo cp -f "$temp_hosts" /etc/hosts

# Remove the temporary file
rm "$temp_hosts"

