#!/usr/bin/env bash
# Fix the web server to run Nginx as the nginx user
sed -i 's/Listen 8080/#&/' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
service nginx restart

