#!/usr/bin/env bash
#Fixes a web server to run nginx as user
sed -i 's/user  nginx;/user  nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf
nginx -g 'daemon off;'
